#ifndef C_FILECONTROL_NEWFILES
#define C_FILECONTROL_NEWFILES

  enum ENUM_FILECONTROL_ERRO{
    FILECONTROL_ERRO_NOERRO,
    FILECONTROL_ERRO_FILENAMENULL,
    FILECONTROL_ERRO_EXTNULL,
    FILECONTROL_ERRO_MAXFILENAMETRIES,
    FILECONTROL_ERRO_DATANULL,
    FILECONTROL_ERRO_INVALIDHANDLE
  };
  
  struct STRUCT_FILECONTROL_CONFIG{
    int maxnametries;
    int commom_flag;
  };


#endif